import io
from fastapi import APIRouter, Query, Response, HTTPException
from fastapi.responses import StreamingResponse
from app.agents.orchestrator import orchestrator

router = APIRouter(prefix="/report", tags=["Report & Analytics"])

@router.get("/pipeline")
async def run_full_pipeline(
    query: str = Query(...),
    persona: str = Query("Assertive"),
    language: str = Query("English"),
    seller_personality: str = Query("Flexible")
):
    """Executes the complete 8-agent end-to-end pipeline in one call."""
    res = await orchestrator.run_full_pipeline(query, persona, language, seller_personality)
    return {"status": "success", "data": res}

@router.get("/pdf")
async def generate_pdf_report(
    query: str = Query("Samsung S24 Ultra"),
    persona: str = Query("Assertive")
):
    """
    Generates a professional, print-ready PDF executive negotiation report.
    """
    # Fetch live pipeline data
    data = await orchestrator.run_full_pipeline(query, persona, "English", "Flexible")
    
    product_name = data.get("product", {}).get("name", query)
    analysis = data.get("price_analysis", {})
    confidence = data.get("opportunity", {}).get("confidence_score", 88)
    summary = data.get("summary", {}).get("summary", "Executive victory report generated by NegoSphere AI.")

    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontSize=22,
            textColor=colors.HexColor('#3F3024'),
            spaceAfter=12
        )
        
        body_style = ParagraphStyle(
            'DocBody',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#2F2F2F'),
            spaceAfter=8
        )

        elements = []
        elements.append(Paragraph(f"<b>NegoSphere Executive Victory Report</b>", title_style))
        elements.append(Paragraph(f"<b>Target Item:</b> {product_name}", body_style))
        elements.append(Paragraph(f"<b>Negotiation Strategy Persona:</b> {persona}", body_style))
        elements.append(Paragraph(f"<b>Opportunity Confidence Score:</b> {confidence}/100", body_style))
        elements.append(Spacer(1, 12))

        # Metrics Table
        table_data = [
            ["Metric", "Value"],
            ["Retail List Price", f"₹{analysis.get('highest_price', 134999):,.2f}"],
            ["Average Market Price", f"₹{analysis.get('average_price', 124500):,.2f}"],
            ["AI Fair Target Price", f"₹{analysis.get('recommended_target_offer', 112000):,.2f}"],
            ["Estimated Savings", f"₹{analysis.get('estimated_savings', 22999):,.2f}"]
        ]
        
        t = Table(table_data, colWidths=[200, 200])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3F3024')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#C9A76A')),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8F6F1')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#C9A76A'))
        ]))
        elements.append(t)
        elements.append(Spacer(1, 16))
        
        elements.append(Paragraph("<b>Executive Summary:</b>", styles['Heading2']))
        elements.append(Paragraph(summary, body_style))

        doc.build(elements)
        buffer.seek(0)

        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=NegoSphere_Report_{query.replace(' ', '_')}.pdf"}
        )
    except ImportError:
        # Fallback raw formatted text file report if ReportLab is absent
        report_content = f"""NegoSphere Executive Victory Report
======================================
Target Product: {product_name}
Persona Strategy: {persona}
Opportunity Score: {confidence}/100

Pricing Breakdown:
------------------
Retail Price: ₹{analysis.get('highest_price', 134999):,.2f}
Average Market Price: ₹{analysis.get('average_price', 124500):,.2f}
AI Target Fair Offer: ₹{analysis.get('recommended_target_offer', 112000):,.2f}
Estimated Net Savings: ₹{analysis.get('estimated_savings', 22999):,.2f}

Executive Summary:
------------------
{summary}
"""
        return Response(
            content=report_content,
            media_type="text/plain",
            headers={"Content-Disposition": f"attachment; filename=NegoSphere_Report_{query.replace(' ', '_')}.txt"}
        )
